[project]
name = "bdd_orm"
version = "0.1"
description = "Projet ORM CF-Tech"
authors = [
    { name="Sanae", email="almassati.sanae@gmail.com" }
]

[tool.setuptools.packages.find]
where = ["app"]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
